# Generated by Django 2.2.7 on 2019-11-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('img', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=100)),
                ('info', models.CharField(blank=True, default='', max_length=1000)),
                ('inCart', models.BooleanField(default=False)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
